### ISSUE TITLE
Plans to support Google-Mobile-Ads-SDK v7.5+?

### ISSUE THREAD

**Issue by strefethen** [bazaarvoice/bv-ios-ads-sdk#1]
Looks like your SDK requires v7.3.1 of the Google Mobile Ads SDK (May 2015) which is now behind by 6 releases.

Any plans to catch up with v7.6?  

EDIT: looks like the podspec is outdated as I see the podfile is updated to v7.5.2

**Comment by JasonJasonJason** [comment]
Good catch -- updated!
Also note: we're working to deprecate this SDK in favor of [bv-ios-sdk](https://github.com/bazaarvoice/bv-ios-sdk) :hushed: 
When complete, we will add `deprecated_in_favor_of` to signify this in cocoapods
